---

- name: install git apt pkgs
  apt:
    name:
      - git
    update_cache: no
  register: git_apt

- name: configure git ssl verify
  community.general.git_config:
    name: http.sslverify
    value: false
    scope: system

- name: initialize git directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  with_items:
    - /root/.ssh

- name: configure git safe directories
  community.general.git_config:
    name: safe.directory
    value: "{{ item }}"
    scope: global
  with_items:
    - /var/www/minilauta-tinyib.git
